# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isg_ai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='isg_ai.proto',
  package='isg_ai',
  syntax='proto2',
  serialized_pb=_b('\n\x0cisg_ai.proto\x12\x06isg_ai\"\x9b\x01\n\rImageMaskPair\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x05\x12\x12\n\nimg_height\x18\x02 \x01(\x05\x12\x11\n\timg_width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x12\n\nmsk_height\x18\x05 \x01(\x05\x12\x11\n\tmsk_width\x18\x06 \x01(\x05\x12\x0c\n\x04mask\x18\x07 \x01(\x0c\x12\r\n\x05label\x18\x08 \x01(\x05\"\x89\x01\n\x0eImageBoxesPair\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x05\x12\x12\n\nimg_height\x18\x02 \x01(\x05\x12\x11\n\timg_width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x11\n\tbox_count\x18\x05 \x01(\x05\x12\r\n\x05\x62oxes\x18\x06 \x01(\x0c\x12\r\n\x05label\x18\x07 \x01(\x05\"i\n\x0fImageNumberPair\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x05\x12\x12\n\nimg_height\x18\x02 \x01(\x05\x12\x11\n\timg_width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x0e\n\x06number\x18\x05 \x01(\x05\"~\n\x12ImageYoloBoxesPair\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x05\x12\x12\n\nimg_height\x18\x02 \x01(\x05\x12\x11\n\timg_width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x11\n\tbox_count\x18\x05 \x01(\x05\x12\r\n\x05\x62oxes\x18\x06 \x01(\x0c')
)




_IMAGEMASKPAIR = _descriptor.Descriptor(
  name='ImageMaskPair',
  full_name='isg_ai.ImageMaskPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='isg_ai.ImageMaskPair.channels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_height', full_name='isg_ai.ImageMaskPair.img_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_width', full_name='isg_ai.ImageMaskPair.img_width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='isg_ai.ImageMaskPair.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msk_height', full_name='isg_ai.ImageMaskPair.msk_height', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msk_width', full_name='isg_ai.ImageMaskPair.msk_width', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask', full_name='isg_ai.ImageMaskPair.mask', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='isg_ai.ImageMaskPair.label', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=180,
)


_IMAGEBOXESPAIR = _descriptor.Descriptor(
  name='ImageBoxesPair',
  full_name='isg_ai.ImageBoxesPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='isg_ai.ImageBoxesPair.channels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_height', full_name='isg_ai.ImageBoxesPair.img_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_width', full_name='isg_ai.ImageBoxesPair.img_width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='isg_ai.ImageBoxesPair.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_count', full_name='isg_ai.ImageBoxesPair.box_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boxes', full_name='isg_ai.ImageBoxesPair.boxes', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='isg_ai.ImageBoxesPair.label', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=320,
)


_IMAGENUMBERPAIR = _descriptor.Descriptor(
  name='ImageNumberPair',
  full_name='isg_ai.ImageNumberPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='isg_ai.ImageNumberPair.channels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_height', full_name='isg_ai.ImageNumberPair.img_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_width', full_name='isg_ai.ImageNumberPair.img_width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='isg_ai.ImageNumberPair.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='isg_ai.ImageNumberPair.number', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=427,
)


_IMAGEYOLOBOXESPAIR = _descriptor.Descriptor(
  name='ImageYoloBoxesPair',
  full_name='isg_ai.ImageYoloBoxesPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='isg_ai.ImageYoloBoxesPair.channels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_height', full_name='isg_ai.ImageYoloBoxesPair.img_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_width', full_name='isg_ai.ImageYoloBoxesPair.img_width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='isg_ai.ImageYoloBoxesPair.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_count', full_name='isg_ai.ImageYoloBoxesPair.box_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boxes', full_name='isg_ai.ImageYoloBoxesPair.boxes', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=555,
)

DESCRIPTOR.message_types_by_name['ImageMaskPair'] = _IMAGEMASKPAIR
DESCRIPTOR.message_types_by_name['ImageBoxesPair'] = _IMAGEBOXESPAIR
DESCRIPTOR.message_types_by_name['ImageNumberPair'] = _IMAGENUMBERPAIR
DESCRIPTOR.message_types_by_name['ImageYoloBoxesPair'] = _IMAGEYOLOBOXESPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageMaskPair = _reflection.GeneratedProtocolMessageType('ImageMaskPair', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEMASKPAIR,
  __module__ = 'isg_ai_pb2'
  # @@protoc_insertion_point(class_scope:isg_ai.ImageMaskPair)
  ))
_sym_db.RegisterMessage(ImageMaskPair)

ImageBoxesPair = _reflection.GeneratedProtocolMessageType('ImageBoxesPair', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEBOXESPAIR,
  __module__ = 'isg_ai_pb2'
  # @@protoc_insertion_point(class_scope:isg_ai.ImageBoxesPair)
  ))
_sym_db.RegisterMessage(ImageBoxesPair)

ImageNumberPair = _reflection.GeneratedProtocolMessageType('ImageNumberPair', (_message.Message,), dict(
  DESCRIPTOR = _IMAGENUMBERPAIR,
  __module__ = 'isg_ai_pb2'
  # @@protoc_insertion_point(class_scope:isg_ai.ImageNumberPair)
  ))
_sym_db.RegisterMessage(ImageNumberPair)

ImageYoloBoxesPair = _reflection.GeneratedProtocolMessageType('ImageYoloBoxesPair', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEYOLOBOXESPAIR,
  __module__ = 'isg_ai_pb2'
  # @@protoc_insertion_point(class_scope:isg_ai.ImageYoloBoxesPair)
  ))
_sym_db.RegisterMessage(ImageYoloBoxesPair)


# @@protoc_insertion_point(module_scope)
